<?php 
$plugin = array(
  
  'title' => t('Page article 2 col 630-300'),
  'category' => t('Sudpresse'),
  'icon' => '2col-630-300-article.png',
  'theme' => '2col-630-300-article',
  'css' => '2col-630-300-article.css',

	'panels' => array(
		'top-content' => t('bloc largeur 100% du haut'),
		'article' => t('article'),
		'middle-content' => t('bloc du milieu colonne 1'),
		'commentaires' => t('commentaires'),
		'col-02' => t('Colonne de droite'),
		'bottom-content' => t('bloc largeur 100% du bas'),
   )
   );
?>
