<?php

define('ROSSEL_ADMIN_PATH', 'admin/rossel');

/**
 * @file rosseladmin.module
 */

/**
 * Implementation of hook_menu().
 */
function rosseladmin_menu() {
  $items = array();
  $items[ROSSEL_ADMIN_PATH] = array(
    'title' => 'Rossel',
    'description' => 'Rossel administration links.',
    'position' => 'right',
    'weight' => 6,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer rossel'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}
