<?php 

/**
 * Implementation of hook_menu
 */
function ccibidirectional_menu(){
  $items = array();
  
  $items['ccibidirectional/lockinginformations'] = array(
    'title' => t('Return locking information about a package'),
    'page callback' => 'ccibidirectional_page_lockinginformations',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  
  $items['admin/cci/ccibidirectional/configuration'] = array(
    'title' => t('CCI Newsgate - Bidirectional configuration & settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccibidirectional_form_configuration_form'),
    'access arguments' => array('administer cci'),
    'file' => 'includes/ccibidirectional.admin.inc',
  );
  
  return $items;
}

/**
 * Print the string 0 if the package is not locked. 
 * Print the string 1 follow by The package is locked by username if the package is locked
 * 
 * If a prenode exists for the node, the package is locked and 1 is returned. In any other case, 0 is returned.
 */
function ccibidirectional_page_lockinginformations(){
  module_load_include('inc', 'wallyedit', 'includes/Prenode');
  $content = '0';
  if ($_GET['id'] != NULL){
    //Get the node with the external reference equal to the id
    $nodes = wallytoolbox_get_node_by_cckfield(array('field_externalreference' => $_GET['id']));
    if ($nodes != NULL){
      $nid = $nodes[0]->nid;
      //Check if a prenode exists for this node
      if (prenode_exists($nid)){
        $content = '1';
        $prenode = prenode_get($nid);
        //Get the editing user of this prenode
        $editing_user = user_load(array('uid' => $prenode['locked']['uid']));
        $content .= ' The package is locked by: '.$editing_user->name;
      }
    }
  }
  print $content;
}

/**
 * Implementation of hook_prenodeapi
 * @param array $form_state
 * @param string $op
 */
function ccibidirectional_prenodeapi(&$form_state, $op) {
  if ($op == 'load') {
    //Call the cci api to check if the package is locked in the cci system
    //Only if the break has not been cald by the user
    if ($_GET['break'] != TRUE) {
      $lock_enabled = wally_variable_get('ccibidirectional_lock_enabled', '');
      if ($lock_enabled) {
        $wsdl_uri = wally_variable_get('ccibidirectional_ws_wsdluri', '');
        if ($wsdl_uri != '' && $form_state[$form_state['type']]['#node']->field_externalreference[0]['value'] != NULL ) {
          $parameters = array(
            'id' => $form_state[$form_state['type']]['#node']->field_externalreference[0]['value'],
            'extid' => $form_state[$form_state['type']]['#node']->nid,
          );
          //Soap request to Newsgate
          if ($client = cciadmin_load_soapclient($wsdl_uri)) {
            try {
              $result = $client->checkpackage($parameters);
              list($status, $message) = explode(' ', $result->return);
              switch ($status){
                //Package locked in newsgate
                case '1':
                  $form_state['locked']['name'] = $message.' (From Newsgate)';
                  $form_state['locked']['updated'] = time();
                  break;
                //Pagckage reserved in Newsgate
                case '2':
                  break;
                //Error
                case '-1':
                  drupal_set_message(t('The call to the Newsgate webservice for locking information failed, please ask an administrator'), 'error');
                  break;
              }
            } catch (SoapFault $exception) {
              drupal_set_message(t('WebService error while sending the XML: @faultstring', array('@faultstring' => $exception->faultstring)), 'error');
              dsm($exception);
            }
          } else {
            drupal_set_message(t('Unable to check CCI lock, you will not be abled to save this package untill the lock is disabled, <a href="/admin/cci/ccibidirectional/configuration">here</a>'), 'error');
          }
        } else {
          drupal_set_message(t('You have to configure the <a href="/admin/cci/ccibidirectional/configuration">ccibidirectional module</a>'), 'warning');
        }
      } else {
        drupal_set_message(t('To use CCI lock you have to enable it <a href="/admin/cci/ccibidirectional/configuration">here</a>'), 'warning');
      }
    }
  }
}
