<?php
// $Id: qualifio.module $

/**
 *  @file media_qualifio/media_qualifio.module
 *
 *  Embedded Other Field provider file for qualifio.com.
 */

// An include of the variable management file.
include_once('includes/media_qualifio.variables.inc');
/**
 * Implementation of hook_menu().
 */
function media_qualifio_menu() {
  return array(
    'admin/settings/media_qualifio' => array(
      'title' => 'Media: Qualifio',
      'description' => 'Administer the Media: Qualifio module.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('media_qualifio_settings'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/media_qualifio.admin.inc',
    ),
  );
}

/**
 * Implementation of Embedded Media Field's hook_emfield_providers().
 */
function media_qualifio_emfield_providers($module, $provider = NULL) {
  // We know this module only includes the main provider file, avoid needless
  // PHP warnings.
  if ($module == 'emother' && (!isset($provider) || ($provider == 'qualifio'))) {
    static $path;
    // Cache the result for later.
    if (!isset($path)) {
      $found = drupal_system_listing("$provider\.inc$", drupal_get_path('module', 'media_qualifio') ."/includes/providers/$module", 'name', 0);
      if (is_array($found) && !empty($found)) {
        $path = $found;
      }
    }
    return $path;
  }
}

/**
 * Implementation of hook_theme().
 */
function media_qualifio_theme($existing, $type, $theme, $path) {
  return array(
    'media_qualifio' => array(
      'file' => 'media_qualifio.theme.inc',
      'arguments' => array('media' => NULL, 'variables' => array()),
      'path' => $path.'/themes',
      'template' => 'media-qualifio',
    ),
  );
}