<?php
function wallyrsspublish_theme() {
	$path = drupal_get_path('module', 'wallyrsspublish');
	$base = array(
'file' => 'theme.inc',
'path' => "$path/theme",
	);

	require_once "./$path/theme/theme.inc";
	return array(
	      'views_view_row_rss__default_destination_view_feed' => array(
          'arguments' => array('view' => NULL,'options' => NULL,'row'=>NULL),
          'template' => 'views-view-row-rss',
          'original hook' => 'views_view_row_rss',
          'path' => drupal_get_path('module', 'wallyrsspublish') . '/theme',
    ),
       'views_view_rss__default_destination_view_feed' => array(
       'arguments' => array('view' => NULL,'options' => NULL,'rows'=>NULL),
       'template' => 'views-view-rss',
       'original hook' => 'views_view_rss',
       'path' => drupal_get_path('module', 'wallyrsspublish') . '/theme',
    ),
      'pane_wallyrsspublish_wallyrsspublish' => array(
      'arguments' => array( 'content'=> NULL, 'pane' =>NULL, 'display' =>NULL),
      'template' => 'pane-wallyrsspublish-wallyrsspublish',
      'original hook' => 'panels_pane',
      'path' => drupal_get_path('module', 'wallyrsspublish') . '/theme',
    ),
	);
}

function wallyrsspublish_menu() {
	$items = array();
    $items['admin/settings/wallyrsspublish'] = array(
      'title'           => 'Wally rss publish',
      'description'     => 'Administer Wally Rss Publish.',
      'page callback'   => 'drupal_get_form',
      'page arguments'  => array('wallyrsspublish_settingsrss_form'),
      'access callback' =>TRUE,
      'file'            => 'includes/wallyrsspublish.admin.inc',
    );
  return $items;
}

function wallyrsspublish_block($op = 'list', $delta = 0) {
  switch($op) {    
  case 'list' :
  // Énumération des blocs disponibles
  {
    $blocs = array();
    $blocs['wallyrsspublish'] = array(
        'info' => t('Wally rss publish'), 
        'cache' => BLOCK_CACHE_GLOBAL 
    );
    return $blocs;
  }
  case 'view' :
  	// Génération du contenu à afficher pour le block
  	{
  		$bloc = array();
  		if ($delta == 'wallyrsspublish') {

  			// Construction du block
  			$bloc['subject'] = t('Wally rss publish');
  			$bloc['content'] = theme('pane_wallyrsspublish_wallyrsspublish', $content, $pane, $display);
  		}
  		return $bloc;
  	}
  }
  return $block;
}