<?php

/**
 * Implementation of hook_menu()
 */
function wallyrsspublish_menu() {
  $items = array();
  $items['admin/wally/wallyrsspublish'] = array(
    'title'             => t('Wally RSS Publish'),
    'description'       => t('Administer Wally RSS Publish.'),
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('wallyrsspublish_settingsrss_form'),
    'access arguments'  => array('access administration pages'),
    'file'              => 'includes/wallyrsspublish.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_theme()
 */
function wallyrsspublish_theme() {
  $path = drupal_get_path('module', 'wallyrsspublish');
  $base = array(
    'file' => 'theme.inc',
    'path' => "$path/theme",
  );

  require_once "./$path/theme/theme.inc";
  return array(
    'views_view_row_rss' => array(
      'arguments' => array('view' => NULL,'options' => NULL,'row'=>NULL),
      'template' => 'views-view-row-rss',
      'original hook' => 'views_view_row_rss',
      'path' => drupal_get_path('module', 'wallyrsspublish') . '/theme',
    ),
    'views_view_rss' => array(
      'arguments' => array('view' => NULL,'options' => NULL,'rows'=>NULL),
      'template' => 'views-view-rss',
      'original hook' => 'views_view_rss',
      'path' => drupal_get_path('module', 'wallyrsspublish') . '/theme',
    ),
    'views_view_row_rss_json' => array(
      'arguments' => array('view' => NULL,'options' => NULL,'row'=>NULL),
      'template' => 'views-view-row-rss-json',
      'original hook' => 'views_view_row_rss',
      'path' => drupal_get_path('module', 'wallyrsspublish') . '/theme',
    ),
    'views_view_rss_json' => array(
      'arguments' => array('view' => NULL,'options' => NULL,'rows'=>NULL),
      'template' => 'views-view-rss-json',
      'original hook' => 'views_view_rss',
      'path' => drupal_get_path('module', 'wallyrsspublish') . '/theme',
    ),
    'pane_wallyrsspublish_wallyrsspublish' => array(
      'arguments' => array( 'content'=> NULL, 'pane' =>NULL, 'display' =>NULL),
      'template' => 'pane-wallyrsspublish-wallyrsspublish',
      'original hook' => 'panels_pane',
      'path' => drupal_get_path('module', 'wallyrsspublish') . '/theme',
    ),
  );
}

function wallyrsspublish_block($op = 'list', $delta = 0) {
  switch($op) {
    case 'list' :
      // Énumération des blocs disponibles
      $blocs = array();
      $blocs['wallyrsspublish'] = array(
        'info' => t('Wally RSS Publish'), 
        'cache' => BLOCK_CACHE_GLOBAL 
      );
      return $blocs;
    case 'view' :
      // Génération du contenu à afficher pour le block
      $bloc = array();
      if ($delta == 'wallyrsspublish') {
        // Construction du block
        $bloc['subject'] = t('Wally RSS Publish');
        $bloc['content'] = theme('pane_wallyrsspublish_wallyrsspublish', $content, $pane, $display);
      }
      return $bloc;
  }
  return $block;
}

function wallyrsspublish_preprocess_views_view_rss(&$vars) {
  global $base_url;
  global $language;

  $vars['template_file'] = 'views-view-rss-'.$_GET['format'];
  $view     = &$vars['view'];
  $options  = &$vars['options'];
  $items    = &$vars['rows'];
  $presetname='rsspublish_preset';

  $name = str_replace('-', ' ', $view->args[0]);
  $tax = taxonomy_get_term_by_name($name);
  $tid=$tax[0]->tid;
  $descr= check_plain($tax[0]->description);

  $data=db_fetch_array(db_query('SELECT * FROM {rsspublish} WHERE tid= %d',$tid));
  $imagefile = $data['imagefile'];
  $image = db_fetch_array(db_query('SELECT * FROM {files} WHERE filepath= "%s"',$imagefile));

  $variables['head_title'] = array(variable_get('site_name', 'Drupal'));
  $variables['head_title']        = implode(' | ', $variables['head_title']);

  $path_photo = imagecache_create_url($presetname, $image[filepath]);
  $vars['url']= $path_photo;
  $vars['type']= $image[filemime];
  $vars['filesize'] = $image[filesize];
  $vars['title'] = empty($data['title']) ? $variables['head_title'].' : '.$name : $variables['head_title'].' : '.$data['title'];
  $vars['description'] = empty($data['description']) ? $descr : $data['description'];
  $vars['copyright'] = $data['copyright'];

  $style = &$view->style_plugin;
  // Figure out which display which has a path we're using for this feed. If there isn't
  // one, use the global $base_url
  $link_display_id = $view->display_handler->get_link_display();
  if ($link_display_id && !empty($view->display[$link_display_id])) {
    $path = $view->display[$link_display_id]->handler->get_path();
  }

  if ($path) {
    $path = $view->get_url(NULL, $path);
    $url_options = array('absolute' => TRUE);
    if (!empty($view->exposed_raw_input)) {
      $url_options['query'] = $view->exposed_raw_input;
    }

    // Compare the link to the default home page; if it's the default home page, just use $base_url.
    if ($path == variable_get('site_frontpage', 'node')) {
      $path = '';
    }
    $vars['link'] = check_url(url($path, $url_options));
  }

  $vars['langcode'] = check_plain($language->language);
  $vars['namespaces'] = drupal_attributes($style->namespaces);
  $vars['items'] = $items;
  $vars['channel_elements'] = format_xml_elements($style->channel_elements);
}

function wallyrsspublish_preprocess_views_view_row_rss(&$vars) {
  $vars['template_file'] = 'views-view-row-rss-'.$_GET['format'];
  $view     = &$vars['view'];
  $options  = &$vars['options'];
  $item     = &$vars['row'];
  $presetname='rsspublish_preset';
  $presetname_thumb='rsspublish_thumb_preset';

  $nid= $item->nid;
  $my_node = node_load($nid);
  wallycontenttypes_packagepopulate(&$my_node,'show');
  $descr = "";
  if ($my_node->type == 'wally_articlepackage'){
    $mainstory = $my_node->field_mainstory_nodes[0];
    $teaser_length = 300;
    $teaser = theme("wallyct_teaser", $mainstory->field_textbody[0]['value'], $teaser_length, $my_node);

    if (isset($mainstory->field_textchapo[0]['value'])) {
      $descr = $mainstory->field_textchapo[0]['value'];
    }
    else {
      $descr = $teaser;
    }
  }

  foreach ($my_node->field_embededobjects_nodes as $embeded){
    if ($embeded->type == "wally_photoobject"){
      $picture = $embeded;
      break;
    }
  }

  //$imain = $my_node->field_embededobjects_nodes[0];
  $imain = $picture;

  $type = $imain->field_photofile[0]['filemime'];
  $filesize = $imain->field_photofile[0]['filesize'];

  $imainstory = $imain->field_photofile[0]['filepath'];
  if (!empty($imainstory)){
    $file_img = theme('imagecache', $presetname,  $imainstory);
    $path_photo = imagecache_create_url($presetname, $imainstory);
    $path_photo_thumb = imagecache_create_url($presetname_thumb, $imainstory);
    $vars['url'] = $path_photo;
    $vars['url_thumb'] = $path_photo_thumb;
  }
  else{
    $vars['url'] = '';
    $vars['url_thumb'] = '';
  }

  $vars['filesize'] = $filesize;
  $vars['item'] = $item;
  $vars['type']= $type;
  $vars['description'] = check_plain($descr);
  $vars['title'] = check_plain($item->title);
  $vars['link'] = check_url($item->link);
  $vars['item_elements'] = empty($item->elements) ? '' : format_xml_elements($item->elements);
}
