<?php

include_once('wallyfinfo.features.inc');

/**
 *  Implémentation du hook_menu(); 
 */
function wallyfinfo_menu() {
  $items = array();
  
  $items['view/fil_info'] = array(
    'description' => t('Get view display for fil_info.'), 
    'page callback' => 'wallyfinfo_getviewfinfo', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
* Implementation of hook_theme().
*/
function wallyfinfo_theme($existing) {  
  return array(
    'views_view__fil_info__panel_pane_1' => array(
      'arguments' => array('view' => NULL),
      'template' => 'views-view--fil-info--panel-pane-1',
      'original hook' => 'views_view',
      'path' => drupal_get_path('module', 'wallyfinfo') . '/templates',
    ),
    'views_view__fil_info__panel_pane_2' => array(
      'arguments' => array('view' => NULL),
      'template' => 'views-view--fil-info--panel-pane-2',
      'original hook' => 'views_view',
      'path' => drupal_get_path('module', 'wallyfinfo') . '/templates',
    ),
    'views_view__fil_info__panel_pane_3' => array(
      'arguments' => array('view' => NULL),
      'template' => 'views-view--fil-info--panel-pane-3',
      'original hook' => 'views_view',
      'path' => drupal_get_path('module', 'wallyfinfo') . '/templates',
    ),
    'panels_pane' => array(
      'arguments' => array('output' => array(), 'pane' => array(), 'display' => array()),
      'original hook' => 'panels_pane',
      'path' => drupal_get_path('module', 'wallyfinfo') . '/templates',
    ),
  );
}

/**
 *  Implémentation du hook_preprocess_panels_pane(); 
 */
function phptemplate_engine_preprocess_panels_pane(&$variables) {
  $suggestion = array(); 
  $suggestion = wallycontenttypes_getpackagesuggestions($variables, 'panels_pane'); 
  if(count($suggestion)) $variables['template_files'] = array_merge($suggestion, $variables['template_files']);
}

/**
 * Print a HTML list containing the fields returned by one of the display of the 'fil_info' view.
 * 
 * @param string $display_name
 * 	 Name of display in the 'fil_info' view.
 * 	 Example : 'panel_pane_1'.
 * @param int $dest_id
 *   Taxonomy term id ('tid') of the requested destination.
 * 
 * @return
 * 	 No value but print the HTML code.
 */
function wallyfinfo_getviewfinfo($display_name = NULL, $dest_id = NULL, $offset = 0) {
  $all_display = array();
  $cid = 'wallyfinfo_'.str_replace('_', '-', $display_name).'_'.$dest_id.'_'.($offset-($offset%10));
  $cached_display = cache_get($cid);
  
  if ($cached_display == 0 || !isset($cached_display) || empty($cached_display)) {
    $destination = taxonomy_get_term($dest_id);
    $view_results = array();
    $view_results = views_get_view_result('fil_info', $display_name, $dest_id);
    
    foreach ($view_results as $view_result) {
      $display = '';
      $display = '
          <li>
            <div class="'.strtolower($destination->name).'">
              <a href="'.drupal_get_path_alias("/node/".$view_result->nid).'">
                <small>'.date('H:m', check_plain($view_result->node_created)).'</small>
                <h2>'.strtolower($destination->name).check_plain($view_result->node_title).'</h2>
              </a>
            </div>
          </li>
    	';
      $all_display[] = $display;
    }
    
    cache_set($cid, $all_display, 'cache', time() + 60);
  } else {
    $all_display = $cached_display->data;
  }
  
  print $all_display[$offset];
}

/**
 * Return the javascript code to use the jCarousel effect.
 * 
 * @param array $available_dests
 *   Array of the first level 'Destination Path' taxonomy terms.
 * 
 * @return
 * 	 The js code.
 */
function _wallyfinfo_slidecategoryjs($available_dests) {  
  $jscode = '';

  $jscode .= '
  	$(document).ready(function() {
  	  var page_offset = 0;';
  
  // jCarousel effect for the categories menu.
  $jscode .= '
  	  $("#filcat").jcarousel({
  	    wrap: "both",
      	size: '.sizeof($available_dests).',
        visible: 3,
        buttonNextHTML: "<img src=\"'.base_path().drupal_get_path("module", "wallyfinfo").'/images/nexthorizblanc.png\" class=\"next1\"/>",
        buttonPrevHTML: "<img src=\"'.base_path().drupal_get_path("module", "wallyfinfo").'/images/previoushorizblanc.png\" class=\"prev1\"/>",
        buttonNextEvent: "click",
        buttonPrevEvent: "click"
      });
      var carousel2 = $("#filcat").data("jcarousel");
      
      $("#filcat .jcarousel-clip").css("width", "100%");
      $("#filcat .jcarousel-clip").css("height", "100%");
      
      $(".next1").css("float", "right");
      $(".next1").css("width", "15px");
      $(".next1").css("right", "0");
      $(".next1").css("margin-top", "0px");
      $(".next1").css("margin-bottom", "15px");
      $(".next1").css("margin-left", "5px");
      $(".next1").css("cursor", "pointer");
      $(".next1").css("cursor", "hand");
      
      $(".prev1").css("float", "left");
      $(".prev1").css("width", "15px");
      $(".prev1").css("margin-top", "0px");
      $(".prev1").css("margin-bottom", "15px");
      $(".prev1").css("margin-right", "5px");
      $(".prev1").css("cursor", "pointer");
      $(".prev1").css("cursor", "hand");';
  
  $offset = 0;
  foreach ($available_dests as $available_dest) {
    ++$offset;
    $jscode .= '
      carousel2.add('.$offset.', "<a id=\"'.strtolower($available_dest->name).'\">'.$available_dest->name.'</a>");';
  }
  
  $jscode .= '
  	  $("#filcat .jcarousel-clip li").css("text-align", "center");
      carousel2.first = 1;
	  carousel2.reload();';
  
  // jCarousel effect for the items.
  foreach ($available_dests as $available_dest) {
    $jscode .= '
      $("#car'.strtolower($available_dest->name).'").jcarousel({
      	vertical: true,
      	size: 10,
        scroll: 2,
        visible: 4,
        auto: 2,
        animation: "slow",
        buttonNextHTML: "<img src=\"'.base_path().drupal_get_path("module", "wallyfinfo").'/images/next.png\" class=\"next\"/>",
        buttonPrevHTML: "<img src=\"'.base_path().drupal_get_path("module", "wallyfinfo").'/images/previous.png\" class=\"prev\"/>",
        buttonNextEvent: "click",
        buttonPrevEvent: "click"
      });
      var carousel'.$available_dest->name.' = $("#car'.strtolower($available_dest->name).'").data("jcarousel");';
  }
  
  // Hide all categories at start.
  foreach ($available_dests as $key=>$available_dest) {
    $jscode .= '
      $("#car'.strtolower($available_dest->name).'").hide();';
  }
  
  
  foreach ($available_dests as $key=>$available_dest) {
    $jscode .= '
      var currentCarousel = carousel'.$available_dest->name.';
  	  var currentCarouselName = "'.strtolower($available_dest->name).'";
  	  var currentTid = '.$available_dest->tid.'';
    break;
  }
  
  // Definition of the click actions for the categories labels.
  foreach ($available_dests as $key=>$available_dest) {
    $jscode .= '
      $("a#'.strtolower($available_dest->name).'").click(function() {
        page_offset = 0;
        currentCarousel = carousel'.$available_dest->name.';
        currentCarouselName = "'.strtolower($available_dest->name).'";
        currentTid = "'.$available_dest->tid.'";
        reload_carousel(currentCarousel, currentCarouselName, currentTid);
      });';
  }
  
 // Pager events.
  for ($i=1; $i<6; $i++) {
    $jscode .= '
      $(".pager #page'.$i.'").click(function() {
        page_offset = '.(10*($i-1)).';
        reload_carousel(currentCarousel, currentCarouselName, currentTid);
      });';
  }
  
  $jscode .= '
      function reload_carousel(carousel, dest_name, tid) {';
  	// Hide all categories except de concerned and empty all carousels.
    foreach ($available_dests as $av_dest) {
      if ($av_dest->name != $available_dest->name) {
      $jscode .= '
        $("#car'.strtolower($av_dest->name).'").hide();
        $("#car'.strtolower($av_dest->name).' .jcarousel-clip").css("height", "0px");';
      }
      $jscode .= '
      	carousel'.$av_dest->name.'.list.empty();';
        //$("ul#liste'.strtolower($av_dest->name).' li").remove();';
    }
    
    // Show the concerned category, add items to the concerned carousel and restart it.
    $jscode .= '
        $("#car" + dest_name).show();
        $("#car" + dest_name + " .jcarousel-clip").css("height", "300px");
        
        $(".next").css("float", "right");
        $(".next").css("width", "15px");
        $(".next").css("margin-right", "10px");
        $(".next").css("cursor", "pointer");
        $(".next").css("cursor", "hand");
        
        $(".prev").css("float", "left");
        $(".prev").css("width", "15px");
        $(".prev").css("margin-left", "10px");
        $(".prev").css("cursor", "pointer");
        $(".prev").css("cursor", "hand");

        for (offset = 0; offset < 10; offset++) {

          carousel.add(offset+1, $.ajax({
                                   url: "/view/fil_info/panel_pane_1/" + tid + "/" + (offset+page_offset),
                                   async: false
                                 }).responseText);
        }
        
        carousel.first = 1;
  	    carousel.reload();
  	    carousel.startAuto(carousel.options.auto);
	  }
  	});';
  
  return $jscode;
}