<?php 
$plugin = array(
  
  'title' => t('2 colonnes 630-300'),
  'category' => t('Sudpresse'),
  'icon' => '2col-630-300.png',
  'theme' => '2col-630-300',
  'css' => '2col-630-300.css',

	'panels' => array(
		'top-content' => t('bloc largeur 100% du haut'),
		'col-630-first' => t('colonne 1 du haut'),
		'col-300-first' => t('colonne 2 du haut'),
		'middle-content' => t('bloc largeur 100% du milieu'),
		'col-630-second' => t('colonne 1 du bas'),
		'col-300-second' => t('colonne 2 du bas'),
		'bottom-content' => t('bloc largeur 100% du bas'),
   )
   );
?>
