<?php

function wallynewssitemap_menu() {
  $items = array();

  $items['admin/wally/wallysitemap/newssitemap'] = array(
    'title'            => t('News Sitemap'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('wallynewssitemap_admin_settings_page_form'),
    'access arguments' => array('administer sitemaps'),
    'file'             => 'includes/wallynewssitemap.admin.inc',
    'weight'           => 1,
    'type'             => MENU_LOCAL_TASK,
  );

  return $items;
}

function wallynewssitemap_cron() {
  if ($settings = wally_variable_get('wallynewssitemap_sitemaps_settings', FALSE)) {
    $site_infos = wallysitemap_get_site_infos();
    module_load_include('inc', 'wallynewssitemap', 'includes/wallynewssitemap.generate_xml');
    _wallynewssitemap_generate_sitemap_xml($site_infos, $settings);
  }
}

/**
 * Will be called by wallynewssitemap to build default settings.
 */
function wallynewssitemap_default_settings() {
  return array(
    'wallynewssitemap_path' => 'sites/default/files/sitemaps',
    'wallynewssitemap_consolidate_sitemap' => 0,
    'wallynewssitemap_add_images' => 0,
    'wallynewssitemap_add_videos' => 0,
    'wallynewssitemap_publication_name' => variable_get('site_name', ''),
    'wallynewssitemap_tags_fields' => array(),
    'wallynewssitemap_image_preset' => '',
    'wallynewssitemap_image_license' => '',
    'wallynewssitemap_video_preset' => '',
    'wallynewssitemap_default_img' => drupal_get_path('module', 'wallynewssitemap').'/images/default_img.jpg',
    'wallynewssitemap_allow_embed' => 'no',
  );
}
