<?php
// $Id: xmlsitemap_destination.install

/**
 * @file
 * Install and uninstall schema and functions for the xmlsitemap_destination module.
 */

/**
 * Implements hook_uninstall().
 */
function xmlsitemap_destination_uninstall() {
  /*drupal_load('module', 'taxonomy');
  drupal_load('module', 'xmlsitemap');
  $vids = array_keys(taxonomy_get_vocabularies());
  foreach ($vids as $vid) {
    xmlsitemap_link_bundle_delete('taxonomy_term', $vid);
  }*/
}
