<?php 

/**
 * Implementation of hook_perm().
 */
function wallystat_perm() {
  return array(
    'administer statistics',
  );
}

/**
 * Implementation of hook_menu()
 */
function wallystat_menu() {
  $items = array();
  
  $items['admin/wally/wallystat/settings'] = array(
    'title' => t('Wally Statistics Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wallystat_page_admin_form'),
    'access arguments' => array('administer statistics'),
    'description' => 'Allows administrators to set paramaters for this module to function properly.',
    'file' => 'includes/wallystat.admin.inc',
  );
  
  $items['wallystat/showstats/%'] = array(
    'page callback' => 'wallystat_show_stats',
    'page arguments' => array(2),
    'access arguments' => array('access statistics'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/wallystat.stats_follower.inc',
  );
  
  $items['wallystat/setdisplayfollower/%'] = array(
    'page callback' => 'wallystat_set_display_follower',
    'page arguments' => array(2),
    'access arguments' => array('access statistics'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/wallystat.stats_follower.inc',
  );
  
  return $items;
}

/**
 * Implementation of hook_theme()
 */
function wallystat_theme() {
  $module_path = drupal_get_path('module', 'wallystat');
  $base = array(
    'path' => $module_path.'/templates',
    //'file' => 'theme.inc',
  );
  
  return array(
    'wallystat_show_stats_48h' => $base + array(
      'arguments' => array('nid' => NULL, 'width' => 350, 'height' => 300, 'display_title' => TRUE),
      'template' => 'wallystat-show-stats-48h',
    ),
    'wallystat_show_stats_param' => $base + array(
      'arguments' => array('nid' => NULL, 'param_i' => 0, 'params_callback' => array(), 'width' => 240, 'height' => 150),
      'template' => 'wallystat-show-stats-param',
    ),
  );
}

/**
 * Implementation of hook_cron()
 */
function wallystat_cron(){
  print t('WallyStat started : @date', array('@date' => date('Y-m-d H:i:s'))).'<br/>';

  // Fetch the cron semaphore
  $semaphore = wally_variable_get('wallystat_cron_semaphore', FALSE);

  if ($semaphore && (time() - $semaphore) > 3600) {
    // Either cron has been running for more than an hour or the semaphore
    // was not reset due to a database error.
    // Release cron semaphore
    wally_variable_del('wallystat_cron_semaphore');
  } elseif ($semaphore) {
    print t('Process already running.');
  } else {
    module_load_include('inc', 'wallystat', 'includes/wallystat.process');

    // Register shutdown callback
    register_shutdown_function('_wallystat_cron_cleanup');

    // Lock cron semaphore
    wally_variable_set('wallystat_cron_semaphore', time());

    // Call the function calling the flows
    _wallystat_process_cron();

    // Release cron semaphore
    wally_variable_del('wallystat_cron_semaphore');
  }

	print t('WallyStat finished : @date', array('@date' => date('Y-m-d H:i:s'))).'<br/>';
}

function wallystat_init() {
  if (arg(0) == 'node' && arg(1) != '' && is_numeric(arg(1)) && arg(2) == NULL) {
    if ($vars['node'] = node_load(arg(1))) {
      module_load_include('inc', 'wallystat', 'includes/wallystat.updater_helpers');
      _wallystat_add_updater_callback($vars);
    }
  }
}

/**
 * Implementation of hook_views_api().
 */
function wallystat_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'wallystat') .'/views',
  );
}

/**
 * Theme preprocess function for views-view-row-unformatted.tpl.php
 */
function wallystat_preprocess_wallyctools_row_redacblock(&$vars) {
  if (wally_variable_get('wallystat_display_follower', 0)) {
    $nid = $vars['row']->{$vars['field_alias']};
    $vars['node'] = '<div class = "wallystat_follower" id = "'.$nid.'">'.$vars['node'].'</div>';
    drupal_add_js(drupal_get_path('module', 'wallystat').'/scripts/display_stats_follower.js');
  }
}

/**
 * Implementation of hook_views_admin_links_alter()
 * Add link to activate the statistics follower
 */
function wallystat_views_admin_links_alter(&$vars, $view) {
  if (isset($view->wallyedit_preview) && $view->wallyedit_preview) {
    $vars = array();
  } else {
    if (get_class($view) == 'redac_view') {
      if (wally_variable_get('wallystat_display_follower', 0)) {
        $vars[] = array(
          'title' => t('Disable live statistics'),
          'alt' => t('Disable statistics displayer'),
          'href' => 'wallystat/setdisplayfollower/0',
          'query' => 'destination='.$_GET['q'],
        );
      } else {
        $vars[] = array(
          'title' => t('Enable live statistics'),
          'alt' => t('Enable statistics displayer'),
          'href' => 'wallystat/setdisplayfollower/1',
          'query' => 'destination='.$_GET['q'],
        );
      }
    }
  }
}
