<?php

/**
 * Implementation of hook_menu()
 */
function responsesimulator_menu() {
  $items = array();

  $base = array(
    'access arguments' => array('manage simulated HTTP responses'),
    'file' => 'includes/responsesimulator.admin.inc',
  );

  $items['admin/settings/responsesimulator'] = $base + array(
    'title' => t('HTTP Response Simulator'),
    'page callback' => 'responsesimulator_page_admin_http_responses_list',
    'description' => t('Manage simulated HTTP responses.'),
  );

  $items['admin/settings/responsesimulator/list'] = $base + array(
    'title' => t('List'),
    'description' => t('Listing of the actual HTTP responses.'),
    'page callback' => 'responsesimulator_page_admin_http_responses_list',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight'=> 0,
  );

  $items['admin/settings/responsesimulator/add'] = $base + array(
    'title' => t('Add'),
    'description' => t('Add a new HTTP response or edit an existing one.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('responsesimulator_page_admin_http_responses_add'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  $items['admin/settings/responsesimulator/delete/%'] = $base + array(
    'title' => t('Delete'),
    'description' => t('Page callback to confirm suppression of an HTTP response.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('responsesimulator_page_admin_http_responses_delete', 4),
    'type' => MENU_CALLBACK,
  );

  $items['responsesimulator/%'] = array(
    'page callback' => 'responsesimulator_process_response',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'file' => 'includes/responsesimulator.responses.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function responsesimulator_perm() {
  return array('manage simulated HTTP responses');
}

/**
 * Get a defined HTTP response informations.
 *
 * @param string $rid
 *   The ID or name of the HTTP response to get
 *
 * @return array|NULL
 *   The HTTP response informations if found, NULL otherwise
 */
function responsesimulator_get_defined_http_response($rid) {
  $db_result = db_query("SELECT * FROM {responsesimulator_responses} WHERE rid = %d", $rid);
  if ($result = db_fetch_array($db_result)) {
    $result['settings'] = unserialize($result['settings']);
    return $result;
  }

  // If no matcing rid found, try with the name
  $db_result = db_query("SELECT * FROM {responsesimulator_responses} WHERE name = '%s'", $rid);
  if ($result = db_fetch_array($db_result)) {
    $result['settings'] = unserialize($result['settings']);
    return $result;
  }

  return NULL;
}
