<?php 
$plugin = array(
  
  'title' => t('3 colonnes sur 300'),
  'category' => t('Sudpresse'),
  'icon' => '3col-300-300-300.png',
  'theme' => '3col-300-300-300',
  'css' => '3col-300-300-300.css',

	'panels' => array(
		'top-content' => t('bloc largeur 100% du haut'),
		'col-300a-first' => t('colonne 1 du haut'),
		'col-300b-first' => t('colonne 2 du haut'),
		'col-300-first' => t('colonne 3 du haut'),
		'middle-content' => t('bloc largeur 100% du milieu'),
		'col-300a-second' => t('colonne 1 du bas'),
		'col-300b-second' => t('colonne 2 du bas'),
		'col-300-second' => t('colonne 3 du bas'),
		'bottom-content' => t('bloc largeur 100% du bas'),
   )
   );
?>
