<?php 

/**
 * 
 * Implementation of hook_menu()
 */
function wallyimport_destination_menu(){
	
	$items = array();
	$items['admin/build/import/destination'] = array(
			'title' => t('Wally import destination'),
			'page callback' => 'drupal_get_form',
			'page arguments' => array('wallyimport_destination_form'),
			'access arguments' => array('administer wally import destination'),
			'description'      => t('Import your destination with yaml file'),
			'file'             => 'includes/wallyimport_destination.admin.generate_tree.inc',
	);
	
	return $items;
}