<?php 

/**
 * Implementation of hook_wallymport_importer 
 */
function wallyimportpackage_wallymport_importer(){
  $module_path = './'.drupal_get_path('module', wallyimportpackage);
  return array(
    'wallyimportpackage' => array( 
      array(
  	    'importer_type' => 'packages',
  	    'importer_functions' => array(
  		    'wallyimportpackage',
          'autre',
        ),
        'includes' => array(
          $module_path.'/wallyimportpackage.inc',
        ),
      ),
    ),
    'wallyimportpackageV15' => array(
      array(
        'importer_type' => 'packages',
        'importer_functions' => array(
          'wallyimportpackageV15',
  		    'wallyimportpackage',
        ),
        'includes' => array(
          $module_path.'/wallyimportpackageV15.inc',
          $module_path.'/wallyimportpackage.inc',
        ),
      ),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function wallyimportpackage_menu() {
  $items = array();
  $items['admin/wally/wallyimportpackage/settings'] = array(
    'title'            => t('Wally Import Package Settings'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('wallyimportpackage_page_admin_form'),
    'access arguments' => array('administer wallymport'),
    'description'      => t('Allows administrators to set paramaters for this module to function properly.'),
    'file'             => 'includes/wallyimportpackage.admin.inc',
  );
  $items['admin/wally/wallyimportpackage/settings/general'] = array(
    'title'            => t('General'),
    'page callback'    => 'drupal_get_form',
    'page_arguments'   => array('wallyimportpackage_page_admin_form'),
    'access arguments' => array('administer wallymport'),
    'description'      => t('Allows administrators to set paramaters for this module to function properly.'),
    'file'             => 'includes/wallyimportpackage.admin.inc',
    'weight'           => -3,
    'type'             => MENU_DEFAULT_LOCAL_TASK,
  );
  return $items;
}

/**
 * @} End of "defgroup wallymport.field".
 */
