<?php 
$plugin = array(
  'title' => t('Bricks Default'),
  'category' => t('The Unfolded'),
  'icon' => 'base-layout-brick.png',
  'theme' => 'base-layout-brick',
  'css' => 'base-layout-brick.css',
  'admin css' => 'admin-base-layout-brick.css',
  'panels' => array(
    'contenttop' => t('Content Top'),
		'maincontentleft' => t('Main Content Left'),
		'maincontentright' => t('Main Content Right'),
		'complementary' => t('Complementary'),
    'subcontentleft' => t('Sub Content Left'),
    'subcontentright' => t('Sub Content Right'),
    'contentbottom' => t('Content Bottom'),
)
);
?>









