<?php

/**
 * Implementation of the hook_module
 */
function ccimapping_menu(){
  $items = array();

  $items['admin/cci/ccimapping/configuration'] = array(
    'title' => t('CCI Newsgate - Mapping configuration & settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccimapping_form_configuration_form'),
    'access arguments' => array('administer cci'),
    'file' => 'includes/ccimapping.admin.inc',
  );

  $items['admin/cci/ccimapping/packagetype/editor'] = array(
    'title' => t('Packagetype Editor'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccimapping_form_packagetype_editor_form', 5),
    'access arguments' => array('administer cci'),
    'file' => 'includes/packagetype.editor.inc',
  );

  $items['admin/cci/ccimapping/productinfo/editor'] = array(
    'title' => t('Product Info editor'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccimapping_form_productinfo_editor_form', 5),
    'access arguments' => array('administer cci'),
    'file' => 'includes/productinfo.editor.inc',
  );
  
  $items['admin/cci/ccimapping/cropsync'] = array(
    'title' => t('Cropings Synchronisation'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ccimapping_cropsync_form_cropings_editor_form'),
    'access arguments' => array('administer cci'),
    'file' => 'includes/ccimapping.cropsync.inc',
  );

  return $items;
}

/**
 * Implementation of the hook_theme
 */
function ccimapping_theme(){
  $path = drupal_get_path('module', 'ccimapping');
  $base = array(
    'file' => 'theme.inc',
    'path' => $path.'/theme',
  );
  return array(
    'ccimapping_typeselector'=>$base + array(
      'arguments'=>array('type'),
    ),
  );
}

function ccimap_type_converter($type){
  $mappings=variable_get('ccimapping_type','');
  $mappings=explode("\n", $mappings);
  foreach ($mappings as $mapping){
    $temp=explode("|", $mapping);
    $correct_mapping[$temp[0]]=$temp[1];
  }
  if(array_key_exists($type, $correct_mapping)){
    return $correct_mapping[$type];
  } else {
    return $type;
  }
}
