<?php 
$plugin = array(
  
  'title' => t('3 colonnes 160-480-300'),
  'category' => t('Sudpresse'),
  'icon' => '3col-160-480-300.png',
  'theme' => '3col-160-480-300',
  'css' => '3col-160-480-300.css',

	'panels' => array(
		'top-content' => t('bloc largeur 100% du haut'),
		'col-160-first' => t('colonne 1 du haut'),
		'col-480-first' => t('colonne 2 du haut'),
		'col-300-first' => t('colonne 3 du haut'),
		'middle-content' => t('bloc largeur 100% du milieu'),
		'col-160-second' => t('colonne 1 du bas'),
		'col-480-second' => t('colonne 2 du bas'),
		'col-300-second' => t('colonne 3 du bas'),
		'bottom-content' => t('bloc largeur 100% du bas'),
   )
   );
?>
