<?php

define('CCI_ADMIN_PATH', 'admin/cci');

/**
 * @file cciadmin.module
 */

/**
 * Implementation of hook_menu().
 */
function cciadmin_menu() {
  $items = array();
  $items[CCI_ADMIN_PATH] = array(
    'title' => 'CCI Newsgate',
    'description' => t('CCI administration links.'),
    'position' => 'right',
    'weight' => 6,
    'page callback' => 'system_admin_menu_block_page',
    'access callback' => TRUE,
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function cciadmin_perm() {
  return array(
    'administer cci',
    'edit synchronization datas',
  );
}

/**
 * 
 * Load a soap client
 * @param string $wsdl_uri
 * @return SoapClient|boolean
 */
function cciadmin_load_soapclient($wsdl_uri) {
  try {
    $client = new SoapClient($wsdl_uri, array('features' => SOAP_SINGLE_ELEMENT_ARRAYS, 'trace' => TRUE));
    return $client;
  } catch (SoapFault $exception) {
    drupal_set_message(t('WebService error while creating SOAP client: \n FAULTSTRING: @faultstring\n FAULTCODE: @faultcode', array('@faultstring' => $exception->faultstring, '@faultcode' => $exception->faultcode)), 'error');
  }
  return FALSE;
}