<?php

define('CCI_ADMIN_PATH', 'admin/cci');

/**
 * @file cciadmin.module
 */

/**
 * Implementation of hook_menu().
 */
function cciadmin_menu() {
  $items = array();
  $items[CCI_ADMIN_PATH] = array(
    'title' => 'CCI Newsgate',
    'description' => t('CCI administration links.'),
    'position' => 'right',
    'weight' => 6,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer cci'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}
