<?php

define('BASE_URL', 'http://wally-dev.audaxis.com');
define('WALLY_PATH', '/var/www/wally-dev.audaxis.com');
define('SSO_USER_PROFILE', BASE_URL.'/user');
define('SSO_LIBS_PATH', '/usr/local/lib/ssolibs');
define('SSO_SIMPLESAMLPHP_AUTH_PATH', WALLY_PATH.'/profiles/wally/modules/mod/simplesamlphp_auth');
define('SSO_LOGOUT_PATH', '/simplesaml/sso_logout.php');
define('SSO_FORGET', 'http://pdf.lesoir.be/liseuseSSO/authentification/forget.php');
