<?php
// $Id: media_videortl.module,v 1.0 2011/01/07 ODM $

/**
 *  @file
 *  Embedded Video Field provider file for videortl.com.
 */

/* ***************************************** */
/* INCLUDES                                  */
/* ***************************************** */

// A registry of variable_get defaults.
include_once('includes/media_videortl.variables.inc');

/**
 * Implementation of hook_menu().
 */
function media_videortl_menu() {
  return array(
    'admin/settings/media_videortl' => array(
      'title' => 'Media: videortl',
      'description' => 'Administer the Media: videortl module.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('media_videortl_settings'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/media_videortl.admin.inc',
    ),
  );
}

/**
 * Implementation of hook_theme().
 */
function media_videortl_theme($existing, $type, $theme, $path) {
  return array(
    'media_videortl_default' => array(
      'arguments' => array('variables' => array()),
      'path' => $path.'/themes',
      'template' => 'media-videortl-default',
    ),
  );
}

/**
 * Implementation of hook_flush_caches().
 */
/*function media_videortl_flush_caches() {
  return array('cache_media_videortl_status');
}*/

/**
 * Implementation of hook_emfield_status().
 */
function media_videortl_emfield_status($item, $field = NULL, $module = 'emvideo') {
  // Return the availability of the video.

  $status = media_videortl_check_status($item['value']);
  return $status;
}

/**
 * Implementation of hook_emfield_providers().
 */
function media_videortl_emfield_providers($module, $provider = NULL) {
  // We know this module only includes the main provider file, avoid needless
  // PHP warnings.
  if ($module == 'emvideo' && (!isset($provider) || ($provider == 'videortl'))) {
    static $path;
    // Cache the result for later.
    if (!isset($path)) {
      $found = drupal_system_listing("$provider\.inc$", drupal_get_path('module', 'media_videortl') ."/providers/$module", 'name', 0);
      if (is_array($found) && !empty($found)) {
        $path = $found;
      }
    }    
    return $path;
  }
}

/**
 * Check the availability of a video.
 */
function media_videortl_check_status($video_id, $reset = FALSE) {

  $status[$video_id] = EMFIELD_STATUS_AVAILABLE;  
  return $status[$video_id];
}
