<?php 


/**
 * Implementation of hook_menu().
 */
function wallyscheduler_menu(){
	
	$items = array();
	

	$items['admin/wally/wallyscheduler/dashboard'] = array(
			'title' => t('WallyScheduler Dashboard'),
			'description' => t('Manage settings related to destinations snapshots'),
			'page callback' => 'wallyscheduler_page_dashboard',
			'access arguments' => array('administer wallyscheduler'),
			'file' => 'includes/wallyscheduler.pages.inc',
	);
	
	//@todo: Check with access callback if a rollback is possible (beware of rollback on rollback),  
	$items['admin/wally/wallyscheduler/create_snapshot'] = array(
			'title' => t('WallyScheduler Create a snapshot from Working copy'),
			'description' => t('Manage settings related to destinations snapshots'),
			'page callback' => 'drupal_get_form',
			'page arguments' => array('wallyscheduler_form_createsnapshot_form'),
			'access arguments' => array('wallyscheduler create snapshot'),
			'file' => 'includes/wallyscheduler.forms.inc',
	);
	$items['admin/wally/wallyscheduler/rollback'] = array(
			'title' => t('WallyScheduler Dashboard'),
			'description' => t('Manage settings related to destinations snapshots'),
			'page callback' => 'wally_scheduler_page_dashboard',
			'access arguments' => array('administer wallyscheduler'),
			'file' => 'includes/wallyscheduler.pages.inc',
	);
		$items['admin/wally/wallyscheduler/rollbackrevert'] = array(
			'title' => t('WallyScheduler Dashboard'),
			'description' => t('Manage settings related to destinations snapshots'),
			'page callback' => 'wally_scheduler_page_dashboard',
			'access arguments' => array('administer wallyscheduler'),
			'file' => 'includes/wallyscheduler.pages.inc',
	);
	return $items;
}

/**
 * Implementation of hook_perm().
 */
function wallyscheduler_perm(){

	return array(
	  'administer wallyscheduler',"make rollback","wallyscheduler create snapshot"		
	);
}

/**
 * Implementation of hook_init().
 */
function wallyscheduler_init(){
	
	if(wally_variable_get('wallyscheduler_workingcopy',NULL)!=NULL){
		drupal_set_message(t("BEWARE ! you are on rollback mode (!rollback_machine_name)",array('!rollback_name'=>wally_variable_get('wallyscheduler_workingcopy',NULL))));
	}
}

/**
 * Implementation of hook_cron().
 */
function wallyscheduler_cron(){
	module_load_include('inc', 'wallyscheduler', 'includes/wallyscheduler.helpers');
	
	_wallyscheduler_clean_old_snapshot();
	//check if it is time tom make a switch
    _wallyscheduler_switch_check();
}


/**
 * Implementation of hook_theme().
 */
function wallyscheduler_theme(){


		
	$path = drupal_get_path('module', 'wallyscheduler');
	$base = array(
			'file' => 'theme.inc',
			'path' => $path.'/theme',
	);
		
	return array(
			'wallyscheduler_dashboard' => $base + array(
					'arguments' => array('variables' => array()),
					'template' => 'wallyscheduler-dashboard',
			),
	);
}